export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILED = "ADD_POST_FAILED"

export const DELETE_POST = "DELETE_POST"
export const UPDATE_POST = "UPDATE_POST"

export const LOAD_POST_FEED = "LOAD_POST_FEED"
export const LOAD_POST_FEED_SUCCESS = "LOAD_POST_FEED_SUCCESS"
export const LOAD_POST_FEED_FAILED = "LOAD_POST_FEED_FAILED"

export const LOAD_PROFILE_POSTS = "LOAD_SELF_POSTS"
export const LOAD_PROFILE_POSTS_SUCCESS = "LOAD_SELF_POSTS_SUCCESS"
export const LOAD_PROFILE_POSTS_FAILED = "LOAD_SELF_POSTS_FAILED"

export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAILED = "LIKE_POST_FAILED"
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS"
export const UNLIKE_POST_FAILED = "UNLIKE_POST_FAILED"

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILED = "DELETE_POST_FAILED"
